### ISSUE TITLE
Best way to locate shared libraries

### ISSUE THREAD

**Issue by pepa65** [c3d/xl#2] opened 2019-04-12 17:45 UTC
After building and `sudo make install` the shared library files for xl and recorder are installed (in `/usr/local/lib`) but not found by the `xl` binary. What is the recommended way to do this? I think usually on installation the path gets embedded by r(un)path.

**Comment by c3d** [comment] 2019-04-12 20:01
Yes, a regression caused by a bad commit in make-it quick, https://github.com/c3d/make-it-quick/commit/3d25a8dcdfab729c41e642cb11fe468be2f68c28. I think the reason I did it was incorrect, I'll revert it.

**Comment by c3d** [comment] 2019-04-12 20:48
Fixed now, and a specific test added to the gitlab CI to ensure this is verified.

**Closed as completed** 2019-04-12 20:48 UTC

**Comment by c3d** [comment] 2019-04-12 20:49
(Also, I forgot to point this out, buf if you want to change the install path, you can use

`make install PREFIX=/path/to/prefix/`

Do not forget the trailing /
